name: security
on: push
permissions:
  security-events: write
  actions: read
  contents: read
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
     - name: Git_checkout
       uses: actions/checkout@v4
     - name: codeql_init
       uses: github/codeql-action/init@v4
       with:
         languages: python
         
     - name: codeql_analyse
       uses: github/codeql-action/analyze@v4
       
