name: security
on: push
permissions:
  security-events: write
  actions: read
  contents: read
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
     - name: Git checkout
       uses: actions/checkout@v4
     - name: codeql init
       uses: github/codeql-action/init@v4
       with:
         languages: python
         queries: security-extended, +security-and-quality
     - name: codeql analyze
       uses: github/codeql-action/analyze@v4
       
       
