name: security pipeline
on: [push]
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: git_checkout
        uses: actions/checkout@v4
      - name: sast_sonnar
        run: sonnar-scanner
       
      
